#!/bin/bash
command -v mdcat &>/dev/null || "${0%/*}/mdcat-get.sh"; hash -r
command -v mdcat &>/dev/null || { echo "Error: mdcat required but not available." >&2; exit 1; }
WIDTH=$(if [ $(tput cols) -ge 105 ]; then echo 100; else echo $(( $(tput cols) - 5 )); fi)
mdcat --columns="$WIDTH" <(cat <<'EOF'


Linux Mint (and many other distributions) may have additional password complexity settings in /etc/login.defs or may use a PAM module not explicitly listed in common-password. The obscure option in pam_unix.so enforces a basic level of complexity.

In your case, Linux Mint seems to be enforcing a minimum password length and/or other complexity requirements.

PASS_MIN_LEN=8

*** This is not set on Linux Mint...

*** Final answer is in /etc/pam.d
200~password   [success=1 default=ignore]   pam_unix.so obscure yescrypt
# The obscure option contains obscure option, which might apply some basic complexity checks. If you'd like to remove or relax this, you can adjust the line:



/etc/pam.d/common-password

To disable password complexity requirements:

Find a line similar to this:

password requisite pam_pwquality.so retry=3 minlen=8 minclass=3

or

password requisite pam_cracklib.so retry=3 minlen=8 minclass=3

You can either comment it out by adding a # at the beginning of the line:

# password requisite pam_pwquality.so retry=3 minlen=8 minclass=3

Alternatively, you can reduce the requirements, for example, setting minlen to 6 or lowering minclass:

password requisite pam_pwquality.so retry=3 minlen=6 minclass=1

    minlen: Minimum length of the password (e.g., minlen=6 for a 6-character password).
    minclass: Minimum number of character classes required (e.g., minclass=1 for no specific character classes like upper, lower, digits, symbols).

To disable the complexity check entirely:

You can simply remove or comment out the lines related to pam_pwquality.so or pam_cracklib.so.

EOF
) | less -R
