#!/bin/bash
# Author: Roy Wiseman 2025-05

INI_FILE="$HOME/.angband/Angband.ini"

# Define all options: name|default|description
OPTIONS=(
  "smart_learn|yes|Monsters learn from the player's attacks and resistances."
  "smart_cheat|yes|Monsters know the player's resistances innately (for difficulty)."
  "flow_by_sound|yes|Monsters can track the player by sound (makes stealth more meaningful)."
  "flow_by_smell|yes|Monsters can follow player's scent trail."
  "view_yellow_lite|yes|Show bright yellow circle for light radius."
  "view_bright_lite|yes|Use bright white for overlapping light sources."
  "view_granite_lite|yes|Walls within the player's light radius are shown more clearly."
  "view_special_lite|yes|Special lighting for walls and floors."
  "view_perma_grids|yes|Remember floor tiles the player has seen."
  "view_torch_grids|yes|Remember objects in torchlight range."
  "center_player|yes|Keep the player centered on screen when possible."
  "hilite_player|yes|Highlight the player's position with an outline or effect."
  "avoid_abort|yes|Never automatically quit due to errors; just show messages."
  "avoid_other|no|Avoid picking up unwanted objects automatically. (Disabled: can block good loot)"
  "pickup_detail|yes|Show detailed messages when picking things up."
  "pickup_inven|yes|Automatically pick up items that go to inventory."
  "pickup_only|no|Only pick up items that match the inventory. (Disabled: too restrictive for normal play)"
  "pickup_always|no|Always pick up everything. (Disabled: gets messy)"
  "show_labels|yes|Show labels for inventory slots."
  "show_weights|yes|Display item weights in inventory and equipment."
  "show_choices|yes|Show all menu options clearly."
  "show_details|yes|Show item details during selection (like damage, to-hit etc.)."
  "ring_bell|no|Ring the terminal bell on errors. (Disabled: annoying on most systems)"
  "disturb_near|yes|Stop resting/running if monster appears nearby."
  "disturb_detect|yes|Stop resting/running if trap or treasure is detected."
  "disturb_state|yes|Stop resting/running on status change (e.g. poison)."
  "disturb_move|no|Stop resting/running when the player moves. (Disabled: counterproductive)"
  "disturb_panel|yes|Stop resting/running when screen panel changes."
  "disturb_multi|yes|Stop repeated actions if something important happens."
  "alert_hitpoint|yes|Alert player when HP is dangerously low."
  "flush_failure|yes|Flush input buffer on failure."
  "flush_disturb|yes|Flush input buffer on disturbance."
  "auto_more|yes|Auto-skip --more-- prompts when nothing dangerous is happening."
)

generate_ini() {
  echo "Creating default Angband advanced options file at: $INI_FILE"
  echo "# Angband Advanced Options" > "$INI_FILE"
  echo "# This file was generated by angband-advanced-options.sh" >> "$INI_FILE"
  echo "" >> "$INI_FILE"
  echo "[Options]" >> "$INI_FILE"
  echo "" >> "$INI_FILE"

  for entry in "${OPTIONS[@]}"; do
    IFS='|' read -r name value description <<< "$entry"
    echo "# $description" >> "$INI_FILE"
    echo "$name=$value" >> "$INI_FILE"
    echo "" >> "$INI_FILE"
  done
}

display_ini() {
  echo
  echo "---------------------------"
  echo "Angband Advanced Options:"
  echo "---------------------------"
  cat "$INI_FILE"
  echo "---------------------------"
}

explain_disabled_options() {
  echo
  echo "Some options were set to 'no' because they may be annoying or limiting:"
  echo
  echo "❌ avoid_other: Can prevent picking up useful items like ammo or potions."
  echo "❌ pickup_only: Restricts pickups to what you already carry — bad for early exploration."
  echo "❌ pickup_always: You’ll fill your inventory with junk immediately."
  echo "❌ ring_bell: Annoying on most systems. Terminal beeps!"
  echo "❌ disturb_move: Defeats the purpose of auto-run or resting."
}

# Main
if [[ ! -f "$INI_FILE" ]]; then
  generate_ini
  display_ini
  explain_disabled_options
else
  echo "INI file already exists at: $INI_FILE"
  echo "Displaying current settings:"
  display_ini
fi

