global:
  scrape_interval: 15s     # How frequently to scrape targets.
  evaluation_interval: 15s # How frequently to evaluate rules.

# A scrape configuration for Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes its own metrics.

  # --- Example: Add these later to monitor other things ---
  #
  # To monitor your host machine (requires node_exporter running on the host or as a container):
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['<YOUR_HOST_IP_OR_HOSTNAME>:9100'] # Replace with your host's IP accessible from Docker
  #
  # To monitor Docker containers (requires cAdvisor running as a container):
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080'] # Assuming a cAdvisor container named 'cadvisor'
